TOKEN = "5124231563:AAE3723-HrMJP7pmBMRM_xc8wByZsN9dfzA"
CHAT_ID = -535276929
CHECK_BOT_SEC = 3600
CHECK_SITE_SEC = 600

data = [
    {
        "title": "Канские ведомости",
        "host": "https://kvgazeta.ru",
        "check_text": "Канские ведомости",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Ленинская искра",
        "host": "https://ленинская.рф/",
        "check_text": "662720, п. Шушенское, ул. Ленина, 65",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Победа",
        "host": "https://pobeda24.ru/",
        "check_text": "postmaster@victory.krasnoyarsk.ru",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Ирбейская правда",
        "host": "https://irbeika.ru",
        "check_text": "Ирбейский район, с. Ирбейское, ул. Ленина, д. 57",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Иланские вести",
        "host": "https://ilanskievesti.ru",
        "check_text": "+73917332297",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Советское причулымье",
        "host": "https://sovet-prich.ru",
        "check_text": "nazarovo@krasmail.ru",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Идринский вестник",
        "host": "https://idr-vestnik.ru",
        "check_text": "lubava@krasmail.ru",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Огни Сибири",
        "host": "https://огни-сибири.рф/",
        "check_text": "г.Шарыпово, мкр.Пионерный, 17/1.",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Маяк севера",
        "host": "https://mayaksevera.ru",
        "check_text": "Туруханск, ул. Спандаряна, 28А",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Присаянье",
        "host": "https://присаянье.рф/",
        "check_text": "Красноярский край, с.Агинское, ул. Советская, д. 159",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Авангард",
        "host": "https://avangardkray.ru/",
        "check_text": "Красноярский край, п. Козулька, пер. Лесной, 4",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Емельяновские веси",
        "host": "https://emelyanovskievesi.ru/",
        "check_text": "663020, Красноярский край, п. Емельяново, ул. Московская, 178",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Земля боготольская",
        "host": "https://zemlyabogotolskaya.ru/",
        "check_text": "662060, Красноярский край, г.Боготол, ул. Советская, 18",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Голос Тюхтета",
        "host": "https://golos-tuhteta.ru/",
        "check_text": "662010, Красноярский край, Тюхтетский округ, с. Тюхтет, ул. Кирова, д. 44",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Вести",
        "host": "https://vesti-uluy.ru/",
        "check_text": "662110, Красноярский край, Большеулуйский район, с. Большой Улуй, ул. Революции, д. 20",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Сельская новь",
        "host": "https://gazeta-selnov.ru/",
        "check_text": "Sn.balahta@yandex.ru",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Новый путь",
        "host": "https://газета-новый-путь.рф/",
        "check_text": "662120, Красноярский край, Бирилюсский район, с.Новобирилюссы, ул.Школьная, 2",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Ангарская правда",
        "host": "https://angarka.info",
        "check_text": "663430 Красноярский край, Богучанский район, с. Богучаны, пер. Больничный, 10Р",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Красное Знамя",
        "host": "https://krasnoeznamia.ru",
        "check_text": "663740, Россия, Красноярский край, Абанский район, п. Абан, ул.Советская, 56",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Грани",
        "host": "http://www.graninow.ru/",
        "check_text": "Новоселовский район, с. Новоселово, ул.Юшкова, д.9",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Нива",
        "host": "https://газетанива.рф/",
        "check_text": "+7 391 382 11 07",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Новое время",
        "host": "http://новоевремя.com/",
        "check_text": "Большемуртинский район, п. Большая Мурта, ул. Свердлова, 82.",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Рабочий",
        "host": "https://газетарабочий.рф/",
        "check_text": "Сосновоборск, ул. Энтузиастов, д. 8.",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Пригород",
        "host": "https://газета-пригород.рф/",
        "check_text": "Берёзовский район, пгт. Берёзовка, ул. Центральная, 54. Второй этаж.",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Вместе с вами",
        "host": "https://gazeta-vmeste.ru/",
        "check_text": "+7 391 402 15 87",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Голос времени",
        "host": "https://голосвремени.рф/",
        "check_text": "663960, город Заозерный, ул. 40 лет Октября, 42",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Сибирский хлебороб",
        "host": "https://sib-hleb.ru/",
        "check_text": "662255, Красноярский край, Ужурский район, ул. Ленина, д. 35",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Манская жизнь",
        "host": "https://mananews.ru/",
        "check_text": "+7 391 492 11 70",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Эхо Турана",
        "host": "https://exoturana.ru/",
        "check_text": "Краснотуранский район, с.Краснотуранск, ул. Ленина, дом 63",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Власть труда",
        "host": "https://vtruda.ru/",
        "check_text": "662608, г. Минусинск, ул. Гоголя, 66",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Сельский труженик",
        "host": "https://st-taseevo.ru/",
        "check_text": "663770, Красноярский край, с.Тасеево, ул.Краснопартизанская, д.2",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Енисейская правда",
        "host": "https://енисейская-правда.рф/",
        "check_text": "+7 391 952 44 19",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Причулымский вестник",
        "host": "https://pv-press.ru/",
        "check_text": "г. Ачинск, м-он 8, дом 1, офис 67",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Вперед",
        "host": "https://vpered24.ru/",
        "check_text": "vpered24@mail.ru",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Тубинские вести",
        "host": "https://tubinka.ru/",
        "check_text": "662910, Россия, Красноярский край, Курагинский район, п. Курагино, ул. Партизанская, д.179.",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Дзержинец",
        "host": "https://dzerzhinskoe.ru/",
        "check_text": "663700, с. Дзержинское Красноярского края, пер. Садовый, 14",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Ангарский рабочий",
        "host": "https://angarochka.ru/",
        "check_text": "663400, Красноярский край, Мотыгинский район, п. Мотыгино, ул. Дачная, 18",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Заря Енисея",
        "host": "https://zaren.ru/",
        "check_text": "662543, Красноярский край, г.Лесосибирск, ул.Победы, д. 1г",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Советское приангарье",
        "host": "https://приангарка.рф/",
        "check_text": "г. Кодинск, ул. Колесниченко, д. 13",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Новая жизнь",
        "host": "https://новаяжизнь-казачинское.рф/",
        "check_text": "663100, Красноярский край, Казачинский район, село Казачинское, ул. Красноармейская, 6",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Знамя труда",
        "host": "https://ztgazeta.ru/",
        "check_text": "662850, Красноярский край, Каратузский район, с.Каратузское, ул. Колхозная, 65",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Тува Медиа Групп",
        "host": "https://tmgnews.ru/",
        "check_text": "667000 Республика Тыва г. Кызыл, ул. Красноармейская, 100",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Проспект Мира",
        "host": "https://prmira.ru/",
        "check_text": "660049, Россия, г. Красноярск, ул. Карла Маркса, д. 38",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Тувинская правда",
        "host": "https://tuvapravda.ru/",
        "check_text": "Красноармейская, д. 100, эт. 2, каб. 206",
        "check_times": 5,
        "check_period_sec": 300,
    },
    {
        "title": "Сетевое издание газеты Шын",
        "host": "https://shyn.ru/",
        "check_text": "667000 Республика Тыва г.Кызыл, ул.Красноармейская, 100, 2 этаж, 206 каб.",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Заря",
        "host": "https://zaria.com.ru/",
        "check_text": "663120, Красноярский край, Пировский район, с. Пировское, ул. Советская, д. 1",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Сельская жизнь",
        "host": "https://selo-life.ru/",
        "check_text": "663040, с.Сухобузимское, ул.Комсомольская, дом 21",
        "check_times": 3,
        "check_period_sec": 300,
    },
    {
        "title": "Северный край",
        "host": "http://severokrai.ru",
        "check_text": "Красноярский край, г. Норильск, ул. Талнахская, 51, оф. 3, 4",
        "check_times": 3,
        "check_period_sec": 300,
    },
]
